//------------------------------------------------------------------------------
// <auto-generated>
//     Localized strings for DemulShooter GUI (Plan B - central resources).
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemulShooter_GUI.Properties
{
    using System;
    using System.Globalization;
    using System.Resources;

    /// <summary>
    /// Central string resources for GUI localization. Set Culture before first use.
    /// </summary>
    internal static class Strings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _culture;

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (_resourceMan == null)
                    _resourceMan = new ResourceManager("DemulShooter_GUI.Properties.Strings", typeof(Strings).Assembly);
                return _resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture for resource lookups.
        /// Set this in Program.Main (or before showing any UI) based on config.
        /// </summary>
        internal static CultureInfo Culture
        {
            get { return _culture ?? CultureInfo.CurrentUICulture; }
            set { _culture = value; }
        }

        /// <summary>
        /// Returns the localized string for the given key.
        /// </summary>
        internal static string Get(string key)
        {
            return ResourceManager.GetString(key, Culture) ?? string.Empty;
        }
    }
}
